name: CI CD Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 'install python'
        uses: actions/setup-python@v5
        with:
        python-version: '3.9'

      - name: 'install dependencies'
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Docker build'
        if: success()
        run: |
          docker build -t new_img .